FUNCTION(ADD_DEPENDENCY LIBRARY_NAME PARENT_BUILD_TARGET)
  SET(DEPENDENCY_LIST "")
  MESSAGE("Adding dependency ${LIBRARY_NAME} to target ${PARENT_BUILD_TARGET}")
  SET(LIBRARY_DIR "${CMAKE_CURRENT_LIST_DIR}/../${LIBRARY_NAME}")


  PARSE_YAML("${LIBRARY_DIR}/kakefile.yaml" NODE_NAMES NODE_VALS NODE_INDENTS)

  FIND_LIST_VALUE("include_dir" "${NODE_NAMES}" "${NODE_VALS}" INCLUDE_DIR)
  FIND_LIST_VALUE("src_dir" "${NODE_NAMES}" "${NODE_VALS}" SOURCE_DIR)
  FIND_LIST_VALUE("lib_name" "${NODE_NAMES}" "${NODE_VALS}" LIBRARY_NAME)
  FIND_LIST_VALUE("dependency" "${NODE_NAMES}" "${NODE_VALS}" DEPENDENCY_LIST)
  FIND_LIST_VALUE("target_properties" "${NODE_NAMES}" "${NODE_VALS}" TARGET_PROPERTIES_LIST)

  FILE(GLOB_RECURSE LIB_SOURCES "${LIBRARY_DIR}/${SOURCE_DIR}/*.cc"
                                "${LIBRARY_DIR}/${SOURCE_DIR}/*.cpp"
                                "${LIBRARY_DIR}/${INCLUDE_DIR}/*.h")


  ADD_LIBRARY(${LIBRARY_NAME} STATIC ${LIB_SOURCES})
  TARGET_INCLUDE_DIRECTORIES(${LIBRARY_NAME} PRIVATE "${LIBRARY_DIR}/${INCLUDE_DIR}")
  TARGET_INCLUDE_DIRECTORIES(${PARENT_BUILD_TARGET} PRIVATE "${LIBRARY_DIR}/${INCLUDE_DIR}")

  # SET_TARGET_PROPERTIES(${LIBRARY_NAME} PROPERTY CXX_STANDARD 14)

  TARGET_LINK_LIBRARIES(${PARENT_BUILD_TARGET} ${LIBRARY_NAME})
  # set mandatory target properties
  FOREACH(DEPENDENCY_NAME ${DEPENDENCY_LIST})
    ADD_DEPENDENCY(${DEPENDENCY_NAME} ${LIBRARY_NAME})
  ENDFOREACH()

  FOREACH(TARGET_PROPERTY ${TARGET_PROPERTIES_LIST})
    STRING(REGEX MATCH "^[^ ]+" PROPERTY_NAME ${TARGET_PROPERTY})
    STRING(REPLACE "${PROPERTY_NAME} " "" PROPERTY_VALUE ${TARGET_PROPERTY})
    # MESSAGE("${TARGET_PROPERTY}")
    # MESSAGE("${PROPERTY_NAME}")
    # MESSAGE("${PROPERTY_VALUE}")
    SET_TARGET_PROPERTIES(${LIBRARY_NAME} PROPERTIES ${PROPERTY_NAME} ${PROPERTY_VALUE})
  ENDFOREACH()
ENDFUNCTION(ADD_DEPENDENCY)
