FUNCTION(ADD_DEPENDENCY LIBRARY_DIR BUILD_TARGET)
  # INCLUDE("${CMAKE_CURRENT_SRC_DIR}/yaml-parser.cmake")
  PARSE_YAML("${LIBRARY_DIR}/kakefile.yaml" NODE_NAMES NODE_VALS)

  FIND_LIST_VALUE("include_dir" "${NODE_NAMES}" "${NODE_VALS}" INCLUDE_DIR)
  MESSAGE("INCLUDE_DIR is " ${INCLUDE_DIR})
  MESSAGE("NODE_NAMES is " "${NODE_NAMES}")
  MESSAGE("NODE_VALS is " "${NODE_VALS}")

  FIND_LIST_VALUE("src_dir" "${NODE_NAMES}" "${NODE_VALS}" SOURCE_DIR)
  FIND_LIST_VALUE("lib_name" "${NODE_NAMES}" "${NODE_VALS}" LIB_NAME)

  FILE(GLOB_RECURSE LIB_SOURCES "${LIBRARY_DIR}/${SOURCE_DIR}/*.cc"
                                "${LIBRARY_DIR}/${SOURCE_DIR}/*.cpp"
                                "${LIBRARY_DIR}/${INCLUDE_DIR}/*.h")

  ADD_LIBRARY(${LIB_NAME} STATIC ${LIB_SOURCES})
  TARGET_INCLUDE_DIRECTORIES(${LIB_NAME} PRIVATE "${LIBRARY_DIR}/${INCLUDE_DIR}")
  TARGET_INCLUDE_DIRECTORIES(${BUILD_TARGET} PRIVATE "${LIBRARY_DIR}/${INCLUDE_DIR}")

  TARGET_LINK_LIBRARIES(${BUILD_TARGET} ${LIB_NAME})
ENDFUNCTION(ADD_DEPENDENCY)
