FUNCTION(ADD_DEPENDENCY LIBRARY_NAME BUILD_TARGET)
  SET(DEPENDENCY_LIST "")
  MESSAGE("Adding dependency ${LIBRARY_NAME} to target ${BUILD_TARGET}")
  SET(LIBRARY_DIR "${CMAKE_CURRENT_LIST_DIR}/../${LIBRARY_NAME}")


  PARSE_YAML("${LIBRARY_DIR}/kakefile.yaml" NODE_NAMES NODE_VALS)

  FIND_LIST_VALUE("include_dir" "${NODE_NAMES}" "${NODE_VALS}" INCLUDE_DIR)
  FIND_LIST_VALUE("src_dir" "${NODE_NAMES}" "${NODE_VALS}" SOURCE_DIR)
  FIND_LIST_VALUE("lib_name" "${NODE_NAMES}" "${NODE_VALS}" LIB_NAME)
  FIND_LIST_VALUE("dependency" "${NODE_NAMES}" "${NODE_VALS}" DEPENDENCY_LIST)

  FILE(GLOB_RECURSE LIB_SOURCES "${LIBRARY_DIR}/${SOURCE_DIR}/*.cc"
                                "${LIBRARY_DIR}/${SOURCE_DIR}/*.cpp"
                                "${LIBRARY_DIR}/${INCLUDE_DIR}/*.h")

  ADD_LIBRARY(${LIB_NAME} STATIC ${LIB_SOURCES})
  TARGET_INCLUDE_DIRECTORIES(${LIB_NAME} PRIVATE "${LIBRARY_DIR}/${INCLUDE_DIR}")
  TARGET_INCLUDE_DIRECTORIES(${BUILD_TARGET} PRIVATE "${LIBRARY_DIR}/${INCLUDE_DIR}")

  TARGET_LINK_LIBRARIES(${BUILD_TARGET} ${LIB_NAME})
  FOREACH(DEPENDENCY_NAME ${DEPENDENCY_LIST})
    ADD_DEPENDENCY(${DEPENDENCY_NAME} ${LIB_NAME})
  ENDFOREACH()
ENDFUNCTION(ADD_DEPENDENCY)
