# CONFIGURE_TART_DEFAULT sets default target properties that are valid across Tart
FUNCTION(CONFIGURE_TART_DEFAULT BUILD_TARGET)
SET_TARGET_PROPERTIES(${BUILD_TARGET} PROPERTIES
  DEBUG_POSTFIX "_debug"
  LIBRARY_OUTPUT_DIRECTORY ${TART_TARGET_DIR}/lib/
  LIBRARY_OUTPUT_DIRECTORY_DEBUG ${TART_TARGET_DIR}/lib/
  LIBRARY_OUTPUT_DIRECTORY_RELEASE ${TART_TARGET_DIR}/lib/
  LIBRARY_OUTPUT_DIRECTORY_RELWITHDEBINFO ${TART_TARGET_DIR}/lib/
  ARCHIVE_OUTPUT_DIRECTORY ${TART_TARGET_DIR}/lib/
  ARCHIVE_OUTPUT_DIRECTORY_DEBUG ${TART_TARGET_DIR}/lib/
  ARCHIVE_OUTPUT_DIRECTORY_RELWITHDEBINFO ${TART_TARGET_DIR}/lib/
  ARCHIVE_OUTPUT_DIRECTORY_RELEASE ${TART_TARGET_DIR}/lib/
)
ENDFUNCTION(CONFIGURE_TART_DEFAULT)
