# CONFIGURE_FOR_IOS_10_3 will configure the BUILD_TARGET for an ARM64/iOS 10.3 device
FUNCTION(CONFIGURE_FOR_IOS_10_3 IOS_BUILD_TARGET)
  SET_TARGET_PROPERTIES(${IOS_BUILD_TARGET} PROPERTIES
    XCODE_ATTRIBUTE_DEBUG_INFORMATION_FORMAT "dwarf-with-dsym"
    XCODE_ATTRIBUTE_GCC_PRECOMPILE_PREFIX_HEADER YES
    XCODE_ATTRIBUTE_IPHONEOS_DEPLOYMENT_TARGET "11.0"
    XCODE_ATTRIBUTE_CODE_SIGN_IDENTITY "iOS Developer"
    XCODE_ATTRIBUTE_DEVELOPMENT_TEAM "XXXX"
    XCODE_ATTRIBUTE_ORGANIZATIONNAME "Tartness"
    XCODE_ATTRIBUTE_SDKROOT "iphoneos"
    XCODE_ATTRIBUTE_GCC_SYMBOLS_PRIVATE_EXTERN YES
    XCODE_ATTRIBUTE_CLANG_ENABLE_OBJC_ARC YES
    XCODE_ATTRIBUTE_COMBINE_HIDPI_IMAGES NO
    XCODE_ATTRIBUTE_TARGETED_DEVICE_FAMILY "1,2"
    XCODE_ATTRIBUTE_VALID_ARCHS "arm64")
ENDFUNCTION(CONFIGURE_FOR_IOS_10_3)

# CONFIGURE_FOR_XCODE_FW will configure the BUILD_TARGET so that, when generating an
# Xcode project, the BUILD_TARGET will be compiled as bundled library with headers, bins and optionally
# some resources as a .framework bundle
FUNCTION(CONFIGURE_FOR_XCODE_FW BUILD_TARGET PUBLIC_HEADERS)
  SET_TARGET_PROPERTIES(${BUILD_TARGET} PROPERTIES
    FRAMEWORK TRUE
    FRAMEWORK_VERSION C
    MACOSX_FRAMEWORK_IDENTIFIER com.tartness.${BUILD_TARGET}
    # MACOSX_FRAMEWORK_INFO_PLIST Info.plist
    PUBLIC_HEADER "${PUBLIC_HEADERS}"
    # XCODE_ATTRIBUTE_GCC_PREFIX_HEADER "${CMAKE_CURRENT_SOURCE_DIR}/Prefix.pch"
    # XCODE_ATTRIBUTE_FRAMEWORK_SEARCH_PATHS "${CMAKE_CURRENT_LIST_DIR}/../../thirdparty/lib"
    XCODE_ATTRIBUTE_CODE_SIGNING_ALLOWED NO
    XCODE_ATTRIBUTE_GCC_SYMBOLS_PRIVATE_EXTERN NO
    # MACOSX_BUNDLE_SHORT_VERSION_STRING ${OPENMAPPER_VERSION}
    # MACOSX_BUNDLE_BUNDLE_VERSION ${OPENMAPPER_VERSION}
    MACOSX_BUNDLE_INFO_STRING "Tartness dyn lib bundled as Framework for iOS"
    MACOSX_BUNDLE_BUNDLE_NAME ${BUILD_TARGET}
    # MACOSX_BUNDLE_COPYRIGHT ${OPENMAPPER_COPYRIGHT_NOTE}
    # MACOSX_BUNDLE_INFO_PLIST ${CMAKE_CURRENT_SOURCE_DIR}/Info.plist.in
  )
ENDFUNCTION(CONFIGURE_FOR_XCODE_FW)
