
  
# Link OpenGL according to target properties
FUNCTION(LINK_OPENGL TARGET_LINKED_TO)
  IF(${TART_TARGET_OS} STREQUAL "iOS")# NOTE: on iOS simply add   "-framework OpenGLES"
ELSEIF(${TART_TARGET_OS} STREQUAL "Android")
  INCLUDE("$ENV{KAPANU_3RD_PARTY_LIBS}/cmake-modules/FindOpenGLES2.cmake")
  TARGET_INCLUDE_DIRECTORIES(${K_VMENGINE_TARGET} PRIVATE ${OPENGLES2_INCLUDE_DIR})
  TARGET_LINK_LIBRARIES(${K_VMENGINE_TARGET} PRIVATE debug ${OPENGLES2_LIBRARIES} optimized ${OPENGLES2_LIBRARIES})
  ELSE()
    FIND_PACKAGE(OPENGL REQUIRED)
    FIND_LIBRARY(OPENGL_LIBRARIES OPENGL)
    TARGET_LINK_LIBRARIES(${TARGET_LINKED_TO} PRIVATE DEBUG ${OPENGL_LIBRARIES} OPTIMIZED ${OPENGL_LIBRARIES})
  ENDIF()
ENDFUNCTION(LINK_OPENGL)
