# PROCESS_PACKAGE_PROPERTIES() Process all entries of the target properties list from a tart.yaml file
#
# FUNCTION(PROCESS_PACKAGE_PROPERTIES PACKAGE_TARGET ENTRIES ENTRY_INDENTS)

# PROCESS_TARGET_PROPERTIES() Process all entries of the target properties list from a tart.yaml file
#
FUNCTION(PROCESS_TARGET_PROPERTIES PACKAGE_TARGET ENTRIES ENTRY_INDENTS)
  GET_ENTRY_VALUES("target_properties" "${ENTRIES}" "${ENTRY_INDENTS}" TARGET_PROPERTIES HAS_SUBTREE)
  TART_DEBUG("Processing target_properties: ${TARGET_PROPERTIES}")
  
  FOREACH(TARGET_PROPERTY ${TARGET_PROPERTIES})
    STRING(REGEX MATCH "^.+[ ]" PROPERTY_KEY "${TARGET_PROPERTY}")
    TART_DEBUG("TARGET_PROPERTY: ${PROPERTY_KEY}")
    STRING(REGEX MATCH "[ ].+$" PROPERTY_VALUE "${TARGET_PROPERTY}")
    TART_DEBUG("TARGET_PROPERTY value: ${PROPERTY_VALUE}")
    SET_TARGET_PROPERTIES(${PACKAGE_TARGET} PROPERTIES "${PROPERTY_KEY}" "${PROPERTY_VALUE}")
  ENDFOREACH()
ENDFUNCTION(PROCESS_TARGET_PROPERTIES)

# PROCESS_CUSTOM_CONFIG_PROPERTIES() Process all entries of the custom configuration properties list from a tart.yaml file
#
FUNCTION(PROCESS_CUSTOM_CONFIG_PROPERTIES PACKAGE_TARGET ENTRIES ENTRY_INDENTS)
  GET_ENTRY_VALUES("custom_configuration_properties" "${ENTRIES}" "${ENTRY_INDENTS}" CUSTOM_CONFIG_PROPERTIES HAS_SUBTREE)
  TART_DEBUG("Processing custom_configuration_properties: ${CUSTOM_CONFIG_PROPERTIES}")
  
  FOREACH(CUSTOM_CONFIG_PROPERTY ${CUSTOM_CONFIG_PROPERTIES})
    GET_ENTRY_VALUES(${CUSTOM_CONFIG_PROPERTY} "${ENTRIES}" "${ENTRY_INDENTS}" SPECIFIC_CONFIG_PROPERTIES HAS_SUBTREE)
    FOREACH(SPECIFIC_CONFIG_PROPERTY ${SPECIFIC_CONFIG_PROPERTIES})
      STRING(REGEX MATCH "^.+[ ]" PROPERTY_KEY "${SPECIFIC_CONFIG_PROPERTY}")
      TART_DEBUG("${CUSTOM_CONFIG_PROPERTY} property: ${PROPERTY_KEY}")
      STRING(REGEX MATCH "[ ].+$" PROPERTY_VALUE "${SPECIFIC_CONFIG_PROPERTY}")
      TART_DEBUG("${CUSTOM_CONFIG_PROPERTY} value: ${PROPERTY_VALUE}")
      SET_TARGET_PROPERTIES(${PACKAGE_TARGET} PROPERTIES "${PROPERTY_KEY}" "${PROPERTY_VALUE}")
    ENDFOREACH()
  ENDFOREACH()
  
ENDFUNCTION(PROCESS_CUSTOM_CONFIG_PROPERTIES)
