# currently unused
# PROCESS_TARGET_DEFAULT_PROPERTIES sets default target properties that are valid across Tart
FUNCTION(PROCESS_TARGET_DEFAULT_PROPERTIES PACKAGE_TARGET ENTRIES ENTRY_INDENTS)
  GET_ENTRY_VALUES("package_path" "${ENTRIES}" "${ENTRY_INDENTS}" PACKAGE_PATH HAS_SUBTREE)
  SET_TARGET_PROPERTIES(${PACKAGE_TARGET} PROPERTIES
    DEBUG_POSTFIX "_debug"
    LIBRARY_OUTPUT_DIRECTORY ${PACKAGE_PATH}/bin/
    LIBRARY_OUTPUT_DIRECTORY_DEBUG ${PACKAGE_PATH}/bin/
    LIBRARY_OUTPUT_DIRECTORY_RELEASE ${PACKAGE_PATH}/bin/
    LIBRARY_OUTPUT_DIRECTORY_RELWITHDEBINFO ${PACKAGE_PATH}/bin/
    ARCHIVE_OUTPUT_DIRECTORY ${PACKAGE_PATH}/bin/
    ARCHIVE_OUTPUT_DIRECTORY_DEBUG ${PACKAGE_PATH}/bin/
    ARCHIVE_OUTPUT_DIRECTORY_RELWITHDEBINFO ${PACKAGE_PATH}/bin/
    ARCHIVE_OUTPUT_DIRECTORY_RELEASE ${PACKAGE_PATH}/bin/
    RUNTIME_OUTPUT_DIRECTORY ${PACKAGE_PATH}/bin/
    RUNTIME_OUTPUT_DIRECTORY_DEBUG ${PACKAGE_PATH}/bin/
    RUNTIME_OUTPUT_DIRECTORY_RELWITHDEBINFO ${PACKAGE_PATH}/bin/
    RUNTIME_OUTPUT_DIRECTORY_RELEASE ${PACKAGE_PATH}/bin/
  )
ENDFUNCTION(PROCESS_TARGET_DEFAULT_PROPERTIES)

# PROCESS_TARGET_DEFAULT_COMPILE_DEFINITIONS() Process default compile definition list 
#
FUNCTION(PROCESS_TARGET_DEFAULT_COMPILE_DEFINITIONS PACKAGE_TARGET ENTRIES ENTRY_INDENTS)
  GET_ENTRY_VALUES("package_path" "${ENTRIES}" "${ENTRY_INDENTS}" PACKAGE_PATH HAS_SUBTREE)
  # TODO write a getPackageVersion function
  IS_DIR_GIT_REPO(${PACKAGE_PATH} DIR_IS_GIT_REPO)
  IF(${DIR_IS_GIT_REPO})
    GET_LAST_GIT_TAG("${PACKAGE_PATH}" GIT_TAG)
    TART_DEBUG("Setting compile def TART_PACKAGE_VERSION=${GIT_TAG}")
    TARGET_COMPILE_DEFINITIONS(${PACKAGE_TARGET} PRIVATE "TART_PACKAGE_VERSION=\"${GIT_TAG}\"")
  ENDIF()
ENDFUNCTION(PROCESS_TARGET_DEFAULT_COMPILE_DEFINITIONS)
