# PROCESS_PACKAGE_COMPILE_DEFINITIONS() Process additional tart.yaml compile definition
#
FUNCTION(PROCESS_PACKAGE_COMPILE_DEFINITIONS PACKAGE_NAME ENTRIES ENTRY_INDENTS)
  PROCESS_TARGET_DEFAULT_COMPILE_DEFINITIONS(${PACKAGE_NAME} "${ENTRIES}" "${ENTRY_INDENTS}")
  PROCESS_TARGET_COMPILE_DEFINITIONS(${PACKAGE_NAME} "${ENTRIES}" "${ENTRY_INDENTS}")
  PROCESS_CUSTOM_CONFIG_COMPILE_DEFINITIONS(${PACKAGE_NAME} "${ENTRIES}" "${ENTRY_INDENTS}")
  PROCESS_TARGET_OS_COMPILE_DEFINITIONS(${PACKAGE_NAME} "${ENTRIES}" "${ENTRY_INDENTS}")
  PROCESS_TARGET_ARCH_COMPILE_DEFINITIONS(${PACKAGE_NAME} "${ENTRIES}" "${ENTRY_INDENTS}")
ENDFUNCTION()


# PROCESS_TARGET_COMPILE_DEFINITIONS() Process entries of the target compile definition list from a tart.yaml file
#
FUNCTION(PROCESS_TARGET_COMPILE_DEFINITIONS PACKAGE_TARGET ENTRIES ENTRY_INDENTS)
  GET_ENTRY_VALUES("target_compile_definitions" "${ENTRIES}" "${ENTRY_INDENTS}" TARGET_COMPILE_DEFINITIONS HAS_SUBTREE)
  TART_DEBUG("Processing target_compile_definitions: ${TARGET_COMPILE_DEFINITIONS}")
  
  FOREACH(TARGET_COMPILE_DEFINITION ${TARGET_COMPILE_DEFINITIONS})
    STRING(STRIP ${TARGET_COMPILE_DEFINITION} TARGET_COMPILE_DEFINITION)
    TARGET_COMPILE_DEFINITIONS(${PACKAGE_TARGET} PRIVATE "${TARGET_COMPILE_DEFINITION}")
  ENDFOREACH()
ENDFUNCTION(PROCESS_TARGET_COMPILE_DEFINITIONS)

# PROCESS_CUSTOM_CONFIG_COMPILE_DEFINITIONS() Process entries of the custom configuration compile definition list from a tart.yaml file
#
FUNCTION(PROCESS_CUSTOM_CONFIG_COMPILE_DEFINITIONS PACKAGE_TARGET ENTRIES ENTRY_INDENTS)
  GET_ENTRY_VALUES("custom_configuration_compile_definitions" "${ENTRIES}" "${ENTRY_INDENTS}" CUSTOM_CONFIGURATIONS HAS_SUBTREE)
  TART_DEBUG("Processing custom_configuration_compile_definitions: ${CUSTOM_CONFIGURATIONS}")
  
  FOREACH(CUSTOM_CONFIG ${CUSTOM_CONFIGURATIONS})
    GET_ENTRY_VALUES(${CUSTOM_CONFIG} "${ENTRIES}" "${ENTRY_INDENTS}" SPECIFIC_CONFIG_COMPILE_DEFINITIONS HAS_SUBTREE)
    FOREACH(SPECIFIC_CONFIG_COMPILE_DEFINITION ${SPECIFIC_CONFIG_COMPILE_DEFINITIONS})
      STRING(STRIP ${SPECIFIC_CONFIG_COMPILE_DEFINITION} SPECIFIC_CONFIG_COMPILE_DEFINITION)
      TARGET_COMPILE_DEFINITIONS(${PACKAGE_TARGET} PRIVATE "${SPECIFIC_CONFIG_COMPILE_DEFINITION}")
    ENDFOREACH()
  ENDFOREACH()
ENDFUNCTION(PROCESS_CUSTOM_CONFIG_COMPILE_DEFINITIONS)

# PROCESS_TARGET_OS_COMPILE_DEFINITIONS() Process entries of the custom configuration compile definition list from a tart.yaml file
#
FUNCTION(PROCESS_TARGET_OS_COMPILE_DEFINITIONS PACKAGE_TARGET ENTRIES ENTRY_INDENTS)
  GET_ENTRY_VALUES("target_os_compile_definitions" "${ENTRIES}" "${ENTRY_INDENTS}" OS_LIST HAS_SUBTREE)
  TART_DEBUG("Processing target_os_compile_definitions: ${OS_LIST}")
  
  FOREACH(CURRENT_OS ${OS_LIST})
    IF(${TART_TARGET_OS} STREQUAL ${CURRENT_ARCH})
      GET_ENTRY_VALUES(${CURRENT_OS} "${ENTRIES}" "${ENTRY_INDENTS}" TARGET_OS_COMPILE_DEFINITIONS HAS_SUBTREE)
      FOREACH(TARGET_OS_COMPILE_DEFINITION ${TARGET_OS_COMPILE_DEFINITIONS})
        STRING(STRIP ${TARGET_OS_COMPILE_DEFINITION} TARGET_OS_COMPILE_DEFINITION)
        TARGET_COMPILE_DEFINITIONS(${PACKAGE_TARGET} PRIVATE "${TARGET_OS_COMPILE_DEFINITION}")
      ENDFOREACH()
    ENDIF()
  ENDFOREACH()
ENDFUNCTION(PROCESS_TARGET_OS_COMPILE_DEFINITIONS)

# PROCESS_TARGET_ARCH_COMPILE_DEFINITIONS() Process entries of the custom configuration compile definition list from a tart.yaml file
#
FUNCTION(PROCESS_TARGET_ARCH_COMPILE_DEFINITIONS PACKAGE_TARGET ENTRIES ENTRY_INDENTS)
  GET_ENTRY_VALUES("target_arch_compile_definitions" "${ENTRIES}" "${ENTRY_INDENTS}" ARCH_LIST HAS_SUBTREE)
  TART_DEBUG("Processing target_arch_compile_definitions: ${ARCH_LIST}")
  
  FOREACH(CURRENT_ARCH ${ARCH_LIST})
    IF(${TART_TARGET_ARCH} STREQUAL ${CURRENT_ARCH})
      GET_ENTRY_VALUES(${CURRENT_ARCH} "${ENTRIES}" "${ENTRY_INDENTS}" TARGET_ARCH_COMPILE_DEFINITIONS HAS_SUBTREE)
      FOREACH(TARGET_ARCH_COMPILE_DEFINITION ${TARGET_ARCH_COMPILE_DEFINITIONS})
        TART_TMP("${TARGET_ARCH_COMPILE_DEFINITION}")
        STRING(STRIP ${TARGET_ARCH_COMPILE_DEFINITION} TARGET_ARCH_COMPILE_DEFINITION)
        TARGET_COMPILE_DEFINITIONS(${PACKAGE_TARGET} PRIVATE "${TARGET_ARCH_COMPILE_DEFINITION}")
      ENDFOREACH()
    ENDIF()
  ENDFOREACH()
ENDFUNCTION(PROCESS_TARGET_ARCH_COMPILE_DEFINITIONS)
