# SET_DEFAULT_PROPERTIES() Set default properties
#
FUNCTION(SET_DEFAULT_PROPERTIES PACKAGE_NAME)
  IF(${TART_TARGET_OS} STREQUAL "iOS")
    CONFIGURE_FOR_IOS(${PACKAGE_NAME})
  ENDIF()
  
  TART_DEBUG("Setting compile def TART_TARGET_OS=${TART_TARGET_OS}")
  TARGET_COMPILE_DEFINITIONS(${PACKAGE_NAME} PUBLIC "TART_TARGET_OS=\"${TART_TARGET_OS}\"")
  
  TART_DEBUG("Setting compile def TART_TARGET_ARCH=${TART_TARGET_ARCH}")
  TARGET_COMPILE_DEFINITIONS(${PACKAGE_NAME} PUBLIC "TART_TARGET_ARCH=\"${TART_TARGET_ARCH}\"")
ENDFUNCTION(SET_DEFAULT_PROPERTIES)
