# SET_DEFAULT_PROPERTIES() Set default properties
#
FUNCTION(SET_DEFAULT_PROPERTIES PACKAGE_NAME)
  IF(${TART_TARGET_OS} STREQUAL "iOS")
    CONFIGURE_FOR_IOS(${PACKAGE_NAME})
  ENDIF()
ENDFUNCTION(SET_DEFAULT_PROPERTIES)
